mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: testuser
    MYSQL_USER: testuser
    MYSQL_PASSWORD: testuser

todoapp:
  namespace: todoapp
  image:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: testuser
    DB_NAME: testuser
    DB_USER: testuser
    DB_PASSWORD: testuser
    DB_HOST: testuser

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"